name: Test e-action

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  e-action:
    runs-on: ubuntu-latest
    name: hello
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run tests
        id: emcee
        uses: avito-tech/Emcee.cloud.action@v0.0.1b
        with:
          emcee_token: ${{ secrets.EMCEE_TOKEN }}
          app_path: https://emcee.cloud/api/v1/file/download/0ecf3b28-a6e6-4c41-9762-55fdd107c6aa#app-debug.apk
          tests_path: https://emcee-cloud-backend.k.avito.ru/file/download/29ca9838-195a-4ae3-8870-9099b3b03169#app-debug-androidTest.apk
          platform: android
          device_os_version: 27
          download_reports: allure
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.emcee.outputs.reports_path }}"
